name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run build
      - name: 📦 Publish to GitHub Package Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: |
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.PAT }}
          if [ "${{ github.event.release.prerelease }}" = "false" ]; then
            npm publish
          else
            npm publish --tag next
          fi
      - name: 📦 Publish to NPM Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set registry https://registry.npmjs.org
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          if [ "${{ github.event.release.prerelease }}" = "false" ]; then
            npm publish
          else
            npm publish --tag next
          fi